apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
  namespace : rabbitmq-worker
  labels:
    app: rabbitmq
spec:
  replicas: 3
  service:
    type: LoadBalancer

